name: CI

on:
  push:
    branches: [ 'master', 'cpsc538b' ]
  pull_request:
    branches: [ 'master', 'cpsc538b' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '16']
        golang-version: ['1.18']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.golang-version }}
    - name: Run tests
      run: sbt "testOnly -- -l org.scalatest.tags.Slow"
    - name: 'Upload Fuzz Test Results on Test Failure (in case there are some)'
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: fuzz-test-results
        path: fuzz_output/*
